mongo_data:
    image: busybox
    volumes:
        - /data/db
mongo:
    image: mongo:3.2
    ports:
        - 27017:27017
    volumes_from:
        - mongo_data
node:
    image: vjacobs/chullo
    links:
        - mongo
    ports:
        - 3000:3000
