mongo_data:
    image: busybox
    volumes:
        - /data/db
mongo:
    image: mongo:3.3
    ports:
        - 27017:27017
    volumes_from:
        - mongo_data
data:
    image: busybox
    volumes:
        - /src/uploads
node:
    build: .
    links:
        - mongo
        - data
    ports:
        - 3000

# nginx:
#     image: nginx
#     ports:
#         - 80:80
#     links:
#         - node
#     volumes:
#         - ./logs/nginx:/var/log/nginx
#         - .:/var/www/html
