mongo_data:
    image: busybox
    volumes:
        - /data/db
mongo:
    image: mongo:3.2
    ports:
        - 27017:27017
    volumes_from:
        - mongo_data
node:
    image: vjacobs/chullo
    links:
        - mongo
    volumes:
        - .:/app
    ports:
        - 3000:3000
    entrypoint: ['nodemon', '/app/dist/app.js']

# nginx:
#     image: nginx
#     ports:
#         - 80:80
#     links:
#         - node
#     volumes:
#         - ./logs/nginx:/var/log/nginx
#         - .:/var/www/html
