version: '2'
services:
    chullo:
        build: .
        environment:
            - MONGO_HOST=mongodb
        ports:
            - 3000:3000
        volumes:
            - chullo_volume:/app/uploads
    # mongodb:
    #     build: containers/mongodb
    #     volumes:
    #         - mongodb_volume:/data/db
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_volume:/data/db
volumes:
    mongodb_volume: ~
    chullo_volume: ~
